### ISSUE TITLE
Looks like holding down right mouse button and moving the mouse does not work

### ISSUE THREAD

**Issue by frankystone** [libsdl-org/sdl2-compat#263]
Found this while editing a map in the SDL2 game [Widelands](https://github.com/widelands/widelands). 

* with `SDL2`: while holding down the right mouse button one can move a map inside the widelands editor while moving the mouse
* with `SDL3` and `SDL2-compat` (version 2.30.51-1): Holding down the right mouse button and moving the mouse has no effect

OS: achlinux

[Related question in the archlinux forum](https://bbs.archlinux.org/viewtopic.php?id=303000)

**Comment by svenstaro** [comment]
I can reproduce this.

**Comment by slouken** [comment]
Can you check to see if https://github.com/libsdl-org/SDL/commit/bc3264130d3e2fd21f471d0f6aaccbe6c9828171 fixes this?

**Comment by slouken** [comment]
I believe this is fixed for the 2.30.52 release. Please let us know if this isn't the case!

**Comment by mpan-pl** [comment]
With sdl3 3.2.22 and sdl2-compat 2.30.52, both built with the same settings as the default Arch packages,[1][2] the issue persists for me. Works on sdl 2.30.9 and 2.30.11.

If that’s of any help, here are two outputs with DEBUG_XINPUT enabled. For each clusters indicate RMB press, move after a short wait, then releasing RMB after short wait.

sdl 3.2.22:
```
window 0x3a00036: ButtonPress (X11 button = 3)window 0x3a00036: updating _NET_WM_USER_TIME to 244055993X11 event type = 28 display = 0x597ea35639d0 window = 0x3a00036window 0x3a00036: PropertyNotify: _NET_WM_USER_TIME changed time=244056022{ 244055993 }X11 event type = 22 display = 0x597ea35639d0 window = 0x3a00036window 0x3a00036: ConfigureNotify! (position: 446,143, size: 800x600)X11 event type = 22 display = 0x597ea35639d0 window = 0x3a00036window 0x3a00036: ConfigureNotify! (position: 446,143, size: 800x600)

X11 event type = 6 display = 0x597ea35639d0 window = 0x3a00036

window 0x3a00036: ButtonRelease (X11 button = 3)
```

sdl 2.30.11:
```
window 0x5edf20805f10: ButtonPress (X11 button = 3)
window 0x5edf20805f10: updating _NET_WM_USER_TIME to 244186840
window 0x5edf20805f10: PropertyNotify: _NET_WM_USER_TIME changed time=244186874
{ 244186840 }
window 0x5edf20805f10: ConfigureNotify! (position: 476,110, size: 800x600)
window 0x5edf20805f10: ConfigureNotify! (position: 476,110, size: 800x600)

***NOTHING HERE ON MOUSE MOVE***

window 0x5edf20805f10: ButtonRelease (X11 button = 3)
```

[1] https://gitlab.archlinux.org/archlinux/packaging/packages/sdl2-compat/-/blob/main/PKGBUILD?ref_type=heads#L20
[2] https://gitlab.archlinux.org/archlinux/packaging/packages/sdl3/-/blob/main/PKGBUILD?ref_type=heads#L55

**Comment by slouken** [comment]
Can you reproduce this with the SDL test programs? You can use Ctrl-G in testwm, for example, to toggle mouse grab, if that's relevant.

**Comment by slouken** [comment]
I can reproduce this, investigating now.

**Comment by slouken** [comment]
This was a bug in SDL3, fixed!

**Comment by frankystone** [comment]
Thanks slouken for your incredible work!

**Comment by slouken** [comment]
You're welcome!
