### ISSUE TITLE
sdl2-compat causing memory issues with SDL2 applications on Arch Linux

### ISSUE THREAD

**Issue by ut316ab** [libsdl-org/sdl2-compat#264]
I'm using arch linux and running amiberry with depends on SDL2. Arch Linux switched from SDL2 to sdl2-compat with SDL3 backend. Amiberry core dumps now with:

double free or corruption (!prev)
Aborted (core dumped)

I ran a backtrace on the amiberry application to try to find where the issue was coming from:

gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x000070236ad883a3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x000070236ad2f120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x000070236ad164c3 in __GI_abort () at abort.c:79
#4  0x000070236ad17354 in __libc_message_impl (fmt=fmt@entry=0x70236aea52f5 "%s\n") at ../sysdeps/posix/libc_fatal.c:134
#5  0x000070236ad926a5 in malloc_printerr (str=str@entry=0x70236aea8540 "double free or corruption (!prev)") at malloc.c:5772
#6  0x000070236ad9493c in _int_free_merge_chunk (av=av@entry=0x7022fc000030, p=0x7022fc12f5f0, size=3776) at malloc.c:4679
#7  0x000070236ad94c3a in _int_free (av=0x7022fc000030, p=p@entry=0x7022fc12f5f0, have_lock=<optimized out>, have_lock@entry=0) at malloc.c:4646
#8  0x000070236ad9750e in __GI___libc_free (mem=0x7022fc12f600) at malloc.c:3398
#9  0x000070236062caf0 in SDL_GetAudioStreamDataAdjustGain (stream=0xc8a9340, voidbuf=0x7022fc03aee0, len=8192, extra_gain=<optimized out>) at /usr/src/debug/sdl3/SDL3-3.2.0/src/audio/SDL_audiocvt.c:1189
#10 0x0000702360621a66 in SDL_PlaybackAudioThreadIterate (device=0x99b49a0) at /usr/src/debug/sdl3/SDL3-3.2.0/src/audio/SDL_audio.c:1151
#11 0x00007023601afd4d in call_process (impl=0xc866380) at ../pipewire/src/pipewire/stream.c:441
#12 call_process (impl=0xc866380) at ../pipewire/src/pipewire/stream.c:434
#13 impl_node_process_output (object=0xc866380) at ../pipewire/src/pipewire/stream.c:1090
#14 0x000070235f07a634 in impl_node_process (object=0xc881a28) at ../pipewire/spa/plugins/audioconvert/audioadapter.c:1693
#15 0x00007023601c1599 in process_node.isra.0 (data=data@entry=0xc89f8f0, nsec=nsec@entry=3040824915785) at ../pipewire/src/pipewire/impl-node.c:1493
#16 0x0000702360192fb2 in node_on_fd_events (source=<optimized out>) at ../pipewire/src/pipewire/impl-node.c:1571
#17 0x000070236b480246 in loop_iterate (object=0xc83ab08, timeout=<optimized out>) at ../pipewire/spa/plugins/support/loop.c:612
#18 0x00007023601b6ce7 in do_loop (user_data=0xc83a8d0) at ../pipewire/src/pipewire/thread-loop.c:294
#19 0x000070236ad862ce in start_thread (arg=<optimized out>) at pthread_create.c:447
#20 0x000070236ae0b29c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

It seems the memory issue is coming from SDL_GetAudioStreamDataAdjustGain ?

I've got an issue open with Amiberry as well, but adding this here, as once I removed sdl2-compat and installed just sdl2 from the AUR this problem goes away.

**Comment by slouken** [comment]
Can you try the latest SDL3 from git to see if that takes care of it? We just fixed some related memory corruption there.

**Comment by ut316ab** [comment]
Yeah I just installed the sdl3-git package from the AUR but the issue remains. Is the fix on a different branch?

**Comment by slouken** [comment]
No, that seems to be the latest. @icculus, do you have any ideas here?

**Comment by icculus** [comment]
Reproduces here with amiberry built from git. I think stack frame 8 was a tail call or something in an optimized build, because the free() that's upsetting it is the one at the end of SDL2AudioDeviceCallbackBridge() in sdl2-compat, which doesn't otherwise show up in the listed stack at all.

Valgrind is not upset by this, though, which might mean it's not a double-free but memory corruption of some sort. Certainly it seems unlikely that free is incorrect, but I need to look at amiberry's audio callback....maybe they free'd the callback's buffer?!

**Comment by icculus** [comment]
AddressSanitizer confirms memory corruption:

```
==1338055==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x520000094f30 at pc 0x7ffff79c8c7f bp 0x7fff28dff750 sp 0x7fff28dfeef8
WRITE of size 8192 at 0x520000094f30 thread T19
    #0 0x7ffff79c8c7e in memmove ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:98
    #1 0xf43303 in unsigned char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char, unsigned char>(unsigned char*, unsigned char*, unsigned char*) /usr/include/c++/13/bits/stl_algobase.h:437
    #2 0xf43232 in unsigned char* std::__copy_move_a2<false, unsigned char*, unsigned char*>(unsigned char*, unsigned char*, unsigned char*) /usr/include/c++/13/bits/stl_algobase.h:506
    #3 0xf43232 in unsigned char* std::__copy_move_a1<false, unsigned char*, unsigned char*>(unsigned char*, unsigned char*, unsigned char*) /usr/include/c++/13/bits/stl_algobase.h:533
    #4 0xf43232 in unsigned char* std::__copy_move_a<false, unsigned char*, unsigned char*>(unsigned char*, unsigned char*, unsigned char*) /usr/include/c++/13/bits/stl_algobase.h:540
    #5 0xf43232 in unsigned char* std::copy<unsigned char*, unsigned char*>(unsigned char*, unsigned char*, unsigned char*) /usr/include/c++/13/bits/stl_algobase.h:633
    #6 0xf43232 in sdl2_audio_callback(void*, unsigned char*, int) /home/icculus/Desktop/amiberry/src/sounddep/sound.cpp:921
    #7 0x7ffff784b5c7 in SDL2AudioDeviceCallbackBridge /home/icculus/projects/sdl2-compat/src/sdl2_compat.c:5683
    #8 0x7ffff32ea7c9 in SDL_GetAudioStreamDataAdjustGain (/usr/local/lib/libSDL3.so.0+0x527c9) (BuildId: eecfe0150fb03f5b5381b67c6cebafb78025680e)
    #9 0x7ffff32e05b3 in SDL_PlaybackAudioThreadIterate (/usr/local/lib/libSDL3.so.0+0x485b3) (BuildId: eecfe0150fb03f5b5381b67c6cebafb78025680e)
    #10 0x7ffff5ba3477  (/lib/x86_64-linux-gnu/libpipewire-0.3.so.0+0x83477) (BuildId: 14af016e612ae8a1d1a3b76c7acbf889c8af17f5)
    #11 0x7ffff5d71339  (/usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so+0x8339) (BuildId: bc11ba2e6fad7af532f43ba853ae7598e0d7468a)
    #12 0x7ffff5d70436  (/usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so+0x7436) (BuildId: bc11ba2e6fad7af532f43ba853ae7598e0d7468a)
    #13 0x7ffff5d71d15  (/usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so+0x8d15) (BuildId: bc11ba2e6fad7af532f43ba853ae7598e0d7468a)
    #14 0x7ffff5bb1c66  (/lib/x86_64-linux-gnu/libpipewire-0.3.so.0+0x91c66) (BuildId: 14af016e612ae8a1d1a3b76c7acbf889c8af17f5)
    #15 0x7ffff792ca41 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #16 0x7ffff7148a93 in start_thread nptl/pthread_create.c:447
    #17 0x7ffff71d5c3b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

0x520000094f30 is located 0 bytes after 3760-byte region [0x520000094080,0x520000094f30)
allocated by thread T19 here:
    #0 0x7ffff79cb9c7 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7ffff33a80c6 in SDL_malloc_REAL (/usr/local/lib/libSDL3.so.0+0x1100c6) (BuildId: eecfe0150fb03f5b5381b67c6cebafb78025680e)

Thread T19 created by T0 here:
    #0 0x7ffff79c31f9 in pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x7ffff5ba923d  (/lib/x86_64-linux-gnu/libpipewire-0.3.so.0+0x8923d) (BuildId: 14af016e612ae8a1d1a3b76c7acbf889c8af17f5)
    #2 0x7ffff5bb28ad in pw_thread_loop_start (/lib/x86_64-linux-gnu/libpipewire-0.3.so.0+0x928ad) (BuildId: 14af016e612ae8a1d1a3b76c7acbf889c8af17f5)
    #3 0x7ffff349b6d9 in PIPEWIRE_OpenDevice (/usr/local/lib/libSDL3.so.0+0x2036d9) (BuildId: eecfe0150fb03f5b5381b67c6cebafb78025680e)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:98 in memmove
Shadow bytes around the buggy address:
  0x520000094c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x520000094d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x520000094d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x520000094e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x520000094e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x520000094f00: 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa
  0x520000094f80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x520000095000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x520000095080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x520000095100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x520000095180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1338055==ABORTING
```

The question is whether we caused it or if real SDL2 was just getting lucky here.

**Comment by icculus** [comment]
My current suspicion is that sdl2-compat is way more variable in how much data it requests in its callback. I'm going to clean that up.

**Comment by icculus** [comment]
I can't coerce amiberry to work here, even with SDL2--likely my fault in this case--so I haven't tested further, but the crash in this bug is fixed. Please upgrade if you can and see if it all starts working.

**Comment by ut316ab** [comment]
This fixed the issue and Amiberry is working fine for me now.

**Comment by slouken** [comment]
Great, thanks for the confirmation!
