### ISSUE TITLE
No keyboard and mouse input in RVGL

### ISSUE THREAD

**Issue by OlegAckbar** [libsdl-org/sdl2-compat#277]
With sdl2-compat I can no longer interact with RVGL using keyboard or mouse.

**Comment by gk7huki** [comment]
Keyboard issues should be fixed with the latest sdl2_compat, see https://github.com/libsdl-org/sdl2-compat/issues/253#issuecomment-2622874115. Can you confirm?

**Comment by OlegAckbar** [comment]
> Keyboard issues should be fixed with the latest sdl2_compat, see [#253 (comment)](https://github.com/libsdl-org/sdl2-compat/issues/253#issuecomment-2622874115). Can you confirm?

The latest `sdl2-compat` didn't fix my issue because turns out it wasn't an issue with `sdl2-compat` but the game itself. I recreated my profile folder in this game and now everything works.
