### ISSUE TITLE
m8c font display glitch

### ISSUE THREAD

**Issue by roterodamus** [libsdl-org/sdl2-compat#355]
Since the update to SDL2-compat, M8C has been encountering visual glitches when rendering bitmap fonts, resulting in empty spaces being displayed as solid blocks. This issue is present across all my CachyOS installations. I currently have sdl2-compat version 2.32.50-1.1 and sdl3 version 3.2.4-1.1 installed.

Link to the m8c project.
[https://github.com/laamaa/m8c](https://github.com/laamaa/m8c)
![Image](https://github.com/user-attachments/assets/e7b9c22e-8698-4880-a35c-1d9ae66cdef3)

**Comment by slouken** [comment]
Hmm, I built and ran it, but I don't have an M8 device, and I don't see any issues on the main screen.  Can you provide a minimal example or create a branch that shows the issue on the main "DEVICE DISCONNECTED" screen?

**Comment by roterodamus** [comment]
I thought that might be the problem. I've been able to recreate the issue in a simple example with some help from AI, but I'm not sure what I'm doing. I hope this is useful.

[https://github.com/roterodamus/m8c-font-issue-sdl2-compat-demo](url)

**Comment by slouken** [comment]
Thanks for the repro case! This is fixed for the next release.

**Comment by roterodamus** [comment]
I'm encountering a new error when trying to run the application:

```
Writing config file to /home/afro/.local/share/m8c/config.ini
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  262
  Current serial number in output stream:  263
```
It might be better to revert this change for now, as the maintainer is aware and is currently working on an SDL3 port.

**Comment by roterodamus** [comment]
Last update did not solve the issue. But the top portion is rendered correctly this time.
![Image](https://github.com/user-attachments/assets/0753eb57-75b1-48f2-b850-25237285f4c2)
The maintainer of the project is aware of the problem, and is also currently porting the project to SDL3.

Someone has made a patch that works with the current version of sdl2-compat and the previous. 
https://github.com/laamaa/m8c/issues/180#issue-2855823157

Tnx for all the hard work in squashing those bugs!
